[package]
name = "control_flow"
version = "0.1.0"
authors = ["Thomas Keck <s-tkeckk@haw-landshut.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
